### ISSUE TITLE
[CMSSitemapBridgeBundle]  Problem with empty configuration

### ISSUE THREAD

**Issue by aflaus-presta** [prestaconcept/open-source-management#13]
CMSSitemapBridgeManager throw an error when configurations is empty.

in_array() expects parameter 2 to be array, null given', '/home/aflaus/LocalWorkspace/github/prestacms-sandbox/vendor/presta/cms-sitemap-bridge-bundle/Presta/CMSSitemapBridgeBundle/Model/CMSSitemapBridgeManager.php', in line 68

You can set an array as default value in configuration.

**Comment by nicolas-joubert** [comment]
@alain-flaus PR done
