### ISSUE TITLE
[Sandbox] Editing website theme zones fails silently 

### ISSUE THREAD

**Issue by bvleur** [prestaconcept/open-source-management#18]
When editing blocks in [theme editor](http://sandbox.prestacms.com/admin/en/cms/theme/edit/creative) it looks like edits go through after pressing save, but the contents never actually changes.

**Comment by nicolas-bastien** [comment]
Yes you're right.

Do you have the same problem on your local install ? Sandbox maybe outdated.

I'm working on our administration bundle to finally tag,  I'll have a look at this after.

**Comment by bvleur** [comment]
Yes. It's reproducible locally.

**Comment by nicolas-bastien** [comment]
@nicolas-joubert can you have a look at this please ?

**Comment by nicolas-bastien** [comment]
@alain-flaus can you have a look at this please ?

**Comment by nicolas-bastien** [comment]
@bvleur this fix it https://github.com/prestaconcept/PrestaCMSCoreBundle/pull/163
-> I tag it as waiting for validation

**Comment by bvleur** [comment]
It did not fix this in my project and the sandbox

I can still reproduce it with a fresh clone of symfony-prestacms with the sandbox and updated deps (to include prestaconcept/PrestaCMSCoreBundle#163).

Symptoms are basically the same. Am I missing something?

**Comment by nicolas-bastien** [comment]
Hi, I saw this morning symfony-prestacms  miss some configuration, I'm working on it with @alain-flaus.
Next PR should fix the problem, I'll ping you when it's done

**Comment by bvleur** [comment]
Hi @nicolas-bastien (or others): Do you have any insight on what's going wrong? I can not figure it out, but maybe if I'm looking in the right direction I can fix this. 

I would really appreciate any hint or tip :)

**Comment by aflaus-presta** [comment]
Hi, I look this many times ago but not found what's wrong.
@nicolas-bastien will try to look it today.
