### ISSUE TITLE
[symfony-prestacms] Error on media admin

### ISSUE THREAD

**Issue by aflaus-presta** [prestaconcept/open-source-management#32]
An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_sonata_media_media_edit" must match "[^/]++" ("" given) to generate a corresponding URL.") in SonataMediaBundle:MediaAdmin:list_custom.html.twig at line 17.

It seems that updating the "doctrine/orm" requirement "~2.4" will fix the problem:
https://github.com/sonata-project/SonataMediaBundle/issues/495

see with @nicolas-joubert

**Comment by nicolas-bastien** [comment]
Implement a functional test please ( with crawler)

**Comment by nicolas-bastien** [comment]
@MatCottet so the PR you're about to do should correct this ?
