### ISSUE TITLE
[Deployment] add $ php app/console doctrine:phpcr:repository:init on update

### ISSUE THREAD

**Issue by nicolas-bastien** [prestaconcept/open-source-management#46]
In order to initialize new technical nodes we need to run a : 

```
$ php app/console doctrine:phpcr:repository:init
```

**Comment by nicolas-bastien** [comment]
@dgaussin can you validate that this issue has been fixed by https://github.com/prestaconcept/PrestaDeploymentBundle/commit/7e09f01499dfa8916c7f45a7cd5f71a7287c4152 ?

**Comment by dgaussin** [comment]
I confirm that presta:deployment:deploy-update launches doctrine:phpcr:repository:init
