### ISSUE TITLE
[Deployment] handle reboot apache

### ISSUE THREAD

**Issue by nicolas-bastien** [prestaconcept/open-source-management#47]
Handle reboot apache with a configuration like we did with the rebuild.

@alain-flaus can you give me the command line to run please ?

**Comment by aflaus-presta** [comment]
sudo /usr/sbin/apachectl -t && echo "apache graceful" && sudo /usr/sbin/apachectl graceful

**Comment by aflaus-presta** [comment]
The command setted in your current Makefile:

update-prod:
    sudo /usr/sbin/apachectl -t 2>&1
    sudo /usr/sbin/apachectl graceful
