### ISSUE TITLE
[Deployment] Build release required bdd

### ISSUE THREAD

**Issue by aflaus-presta** [prestaconcept/open-source-management#51]
Jenkins use test environment to execute all the job configure in build.xml.

In some cases we must execute command in env=prod to prepare the release. Exemple: fos:js-routing:dump (don't know why but it try to access database).

But in current build.xml only test database was created then we need to create the prod one if necessary.

@J-Ben87: can you paste build.xml build-release configuration.

**Comment by nicolas-bastien** [comment]
@dgaussin looks like what you had yesterday ?

**Comment by dgaussin** [comment]
Seems fixed in 2.6.4. See https://github.com/symfony/symfony/issues/12278

**Comment by nicolas-bastien** [comment]
Tested on last 2.6, project with no DB works fine !

For the env question, check this : https://github.com/prestaconcept/PrestaDeploymentBundle/commit/77da390395accbe148719d12e9a655f875a711c8

@alain-flaus I guess we can close ?

**Comment by aflaus-presta** [comment]
ok
